"""Schéma de données multi-TCG

Crée les sept niveaux du modèle, plus les trois tables de référence :

    tcg → expansion → card ─┬→ card_name   (un nom par langue, index trigram)
                            └→ printing    (finition + langue)
                                 ├→ price_snapshot   (un relevé daté par source)
                                 ├→ collection_item  (ce que je possède)
                                 └→ watched_printing (ce que je surveille)

    références : rarity, finish (propres à un TCG), price_source

Généré par `alembic revision --autogenerate`, puis relu et amendé :
le type ENUM `card_condition` est détruit explicitement au downgrade
(voir le commentaire dans `downgrade`).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-15 10:07:20

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('homepage_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tcg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('expansion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tcg_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('series', sa.String(length=256), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('card_count_official', sa.Integer(), nullable=True),
    sa.Column('card_count_total', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('symbol_url', sa.Text(), nullable=True),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tcg_id'], ['tcg.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tcg_id', 'code', name='uq_expansion_tcg_code')
    )
    op.create_index('ix_expansion_external_ids', 'expansion', ['external_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_expansion_tcg_id'), 'expansion', ['tcg_id'], unique=False)
    op.create_table('finish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tcg_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tcg_id'], ['tcg.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tcg_id', 'code', name='uq_finish_tcg_code')
    )
    op.create_index(op.f('ix_finish_tcg_id'), 'finish', ['tcg_id'], unique=False)
    op.create_table('rarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tcg_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tcg_id'], ['tcg.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tcg_id', 'code', name='uq_rarity_tcg_code')
    )
    op.create_index(op.f('ix_rarity_tcg_id'), 'rarity', ['tcg_id'], unique=False)
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expansion_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('number_sort', sa.Integer(), nullable=True),
    sa.Column('rarity_id', sa.Integer(), nullable=True),
    sa.Column('illustrator', sa.String(length=256), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_phash', sa.String(length=64), nullable=True),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expansion_id'], ['expansion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expansion_id', 'number', name='uq_card_expansion_number')
    )
    op.create_index(op.f('ix_card_expansion_id'), 'card', ['expansion_id'], unique=False)
    op.create_index('ix_card_expansion_number_sort', 'card', ['expansion_id', 'number_sort'], unique=False)
    op.create_index('ix_card_external_ids', 'card', ['external_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_card_image_phash'), 'card', ['image_phash'], unique=False)
    op.create_index(op.f('ix_card_rarity_id'), 'card', ['rarity_id'], unique=False)
    op.create_table('card_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_normalized', sa.Text(), sa.Computed('lower(immutable_unaccent(name))', persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'language', name='uq_card_name_card_language')
    )
    op.create_index(op.f('ix_card_name_card_id'), 'card_name', ['card_id'], unique=False)
    op.create_index('ix_card_name_language', 'card_name', ['language'], unique=False)
    op.create_index('ix_card_name_normalized_trgm', 'card_name', ['name_normalized'], unique=False, postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    op.create_table('printing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('finish_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finish_id'], ['finish.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'finish_id', 'language', name='uq_printing_card_finish_language')
    )
    op.create_index(op.f('ix_printing_card_id'), 'printing', ['card_id'], unique=False)
    op.create_index('ix_printing_external_ids', 'printing', ['external_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_printing_finish_id'), 'printing', ['finish_id'], unique=False)
    op.create_index(op.f('ix_printing_language'), 'printing', ['language'], unique=False)
    op.create_table('collection_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printing_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('MT', 'NM', 'EX', 'GD', 'LP', 'PL', 'PO', name='card_condition'), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_currency', sa.String(length=3), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(purchase_price IS NULL) = (purchase_currency IS NULL)', name='ck_collection_item_price_currency_together'),
    sa.CheckConstraint('purchase_price IS NULL OR purchase_price >= 0', name='ck_collection_item_price_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_collection_item_quantity_positive'),
    sa.ForeignKeyConstraint(['printing_id'], ['printing.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_item_printing_id'), 'collection_item', ['printing_id'], unique=False)
    op.create_table('price_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printing_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_type', sa.String(length=64), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_price_snapshot_amount_non_negative'),
    sa.ForeignKeyConstraint(['printing_id'], ['printing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['price_source.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printing_id', 'source_id', 'observed_on', name='uq_price_snapshot_daily')
    )
    op.create_index('ix_price_snapshot_printing_observed', 'price_snapshot', ['printing_id', 'observed_on'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_price_snapshot_source_id'), 'price_snapshot', ['source_id'], unique=False)
    op.create_table('watched_printing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printing_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['printing_id'], ['printing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printing_id', name='uq_watched_printing_printing')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_printing')
    op.drop_index(op.f('ix_price_snapshot_source_id'), table_name='price_snapshot')
    op.drop_index('ix_price_snapshot_printing_observed', table_name='price_snapshot', postgresql_using='btree')
    op.drop_table('price_snapshot')
    op.drop_index(op.f('ix_collection_item_printing_id'), table_name='collection_item')
    op.drop_table('collection_item')
    op.drop_index(op.f('ix_printing_language'), table_name='printing')
    op.drop_index(op.f('ix_printing_finish_id'), table_name='printing')
    op.drop_index('ix_printing_external_ids', table_name='printing', postgresql_using='gin')
    op.drop_index(op.f('ix_printing_card_id'), table_name='printing')
    op.drop_table('printing')
    op.drop_index('ix_card_name_normalized_trgm', table_name='card_name', postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    op.drop_index('ix_card_name_language', table_name='card_name')
    op.drop_index(op.f('ix_card_name_card_id'), table_name='card_name')
    op.drop_table('card_name')
    op.drop_index(op.f('ix_card_rarity_id'), table_name='card')
    op.drop_index(op.f('ix_card_image_phash'), table_name='card')
    op.drop_index('ix_card_external_ids', table_name='card', postgresql_using='gin')
    op.drop_index('ix_card_expansion_number_sort', table_name='card')
    op.drop_index(op.f('ix_card_expansion_id'), table_name='card')
    op.drop_table('card')
    op.drop_index(op.f('ix_rarity_tcg_id'), table_name='rarity')
    op.drop_table('rarity')
    op.drop_index(op.f('ix_finish_tcg_id'), table_name='finish')
    op.drop_table('finish')
    op.drop_index(op.f('ix_expansion_tcg_id'), table_name='expansion')
    op.drop_index('ix_expansion_external_ids', table_name='expansion', postgresql_using='gin')
    op.drop_table('expansion')
    op.drop_table('tcg')
    op.drop_table('price_source')
    # ### end Alembic commands ###

    # `op.drop_table` ne supprime pas le type ENUM créé implicitement avec la
    # table : sans ce DROP, un downgrade suivi d'un upgrade échouerait sur un
    # « type card_condition already exists ».
    postgresql.ENUM(name="card_condition").drop(op.get_bind(), checkfirst=True)
