"""Table de reprise d'import

Les upserts de l'import sont idempotents : le relancer ne duplique rien. Mais
sans mémoire il referait aussi tout le trafic HTTP — 45 000 requêtes pour le
seul corpus Pokémon FR + EN. Cette table note l'extension déjà traitée, par
langue, pour qu'une reprise après interruption ne reprenne que le reste.

En base et non dans un fichier : le conteneur est jetable, la base ne l'est pas.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-15 11:45:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_checkpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('scope_code', sa.String(length=64), nullable=False),
    sa.Column('cards_seen', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'language', 'scope_code', name='uq_import_checkpoint_scope')
    )
    op.create_index(op.f('ix_import_checkpoint_source'), 'import_checkpoint', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_checkpoint_source'), table_name='import_checkpoint')
    op.drop_table('import_checkpoint')
    # ### end Alembic commands ###
