"""Ventes, plateformes de vente, et prix d'achat unitaire

Ajoute `sale_platform` et `collection_sale` (lot 4), et renomme
`collection_item.purchase_price` en `unit_purchase_price`.

Autogénérée puis **corrigée à la main sur deux points** :

1. Le renommage de colonne, qu'Alembic avait traduit en `add_column` +
   `drop_column` — ce qui aurait effacé les prix d'achat sur une base non
   vide. Remplacé par un `alter_column(new_column_name=…)`. Les contraintes
   CHECK suivent le renommage sans intervention : PostgreSQL les stocke par
   référence de colonne, pas par nom.
2. Le type ENUM `card_condition`, réutilisé par `collection_sale`, ne doit
   surtout pas être recréé : il existe depuis la migration 0003. D'où
   `postgresql.ENUM(..., create_type=False)`.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-15 13:26:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('collection_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printing_id', sa.Integer(), nullable=False),
    sa.Column('collection_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', postgresql.ENUM('MT', 'NM', 'EX', 'GD', 'LP', 'PL', 'PO',
                                       name='card_condition', create_type=False), nullable=False),
    sa.Column('unit_sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_currency', sa.String(length=3), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_collection_sale_quantity_positive'),
    sa.CheckConstraint('unit_sale_price >= 0', name='ck_collection_sale_price_non_negative'),
    sa.ForeignKeyConstraint(['collection_item_id'], ['collection_item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['sale_platform.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['printing_id'], ['printing.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_sale_collection_item_id'), 'collection_sale', ['collection_item_id'], unique=False)
    op.create_index(op.f('ix_collection_sale_platform_id'), 'collection_sale', ['platform_id'], unique=False)
    op.create_index(op.f('ix_collection_sale_printing_id'), 'collection_sale', ['printing_id'], unique=False)
    op.create_index(op.f('ix_collection_sale_sale_date'), 'collection_sale', ['sale_date'], unique=False)
    # Renommage, pas un couple add/drop : le nom doit dire que le montant
    # est unitaire, sans perdre les prix déjà saisis.
    op.alter_column(
        'collection_item',
        'purchase_price',
        new_column_name='unit_purchase_price',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'collection_item',
        'unit_purchase_price',
        new_column_name='purchase_price',
    )
    op.drop_index(op.f('ix_collection_sale_sale_date'), table_name='collection_sale')
    op.drop_index(op.f('ix_collection_sale_printing_id'), table_name='collection_sale')
    op.drop_index(op.f('ix_collection_sale_platform_id'), table_name='collection_sale')
    op.drop_index(op.f('ix_collection_sale_collection_item_id'), table_name='collection_sale')
    op.drop_table('collection_sale')
    op.drop_table('sale_platform')
    # ### end Alembic commands ###
